#
# Zend Server 2018.1 EA
#

FROM ubuntu:16.04
LABEL maintainer="jan.burkl@roguewave.com"

ADD ./etc/zend.key /etc/zend.key
RUN cat /etc/zend.key | apt-key add - && \
  echo "deb http://repos.zend.com/zend-server/early-access/2018.1.EA2/lin/deb_apache2.4/ server non-free" >> /etc/apt/sources.list.d/zend-server.list && \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
  zend-server-php-7.2 zend-server-php-7.2-common \
  wget \
  curl \
  vim \
  telnet \
  net-tools \
  inetutils-ping \
  && rm -rf /var/lib/apt/lists/* \
  && rm -f /usr/local/zend/var/libraries/*.bak

ARG PRODUCTION=false

RUN echo "Bootstrapping Zend Server" && \
  /usr/local/zend/bin/zendctl.sh start && \
  /usr/local/zend/bin/zs-manage bootstrap-single-server -p admin -a 'TRUE' --production $PRODUCTION -t 3 -w 5 > /tmp/bootstrap.out && \
  mkdir /webapi && \
  cat /tmp/bootstrap.out | head -n 1 | awk '{print $2}' > /webapi/secret && \
  WEB_API_SECRET=$(cat /webapi/secret) && \
  /usr/local/zend/bin/zs-manage restart -N admin -K $WEB_API_SECRET && \
  /usr/local/zend/bin/zendctl.sh stop && \
  echo export APACHE_ULIMIT_MAX_FILES=\"ulimit -n 4096\" >> /etc/zce.rc && \
  rm -f /usr/local/zend/var/log/*.log

COPY ./etc/run.sh /run.sh
RUN chmod 775 /*.sh

COPY ./etc/shell_functions.rc /shell_functions.rc
COPY ./etc/check_lic.php /check_lic.php

EXPOSE 80
EXPOSE 443
EXPOSE 10081
EXPOSE 10082

CMD ["/run.sh"]
