#
# Zend Server 9.1
#

FROM centos:7
MAINTAINER Jan Burkl <jan@zend.com>

COPY ZendServer-RepositoryInstaller-linux /ZendServer-RepositoryInstaller-linux

COPY functions /etc/rc.d/init.d/functions
COPY nginx_init_centos7 /etc/init.d/nginx
RUN chmod a+x /etc/init.d/nginx /etc/rc.d/init.d/functions

RUN chmod 775 /ZendServer-RepositoryInstaller-linux/*.sh
RUN yum install -y \
  wget \
  curl \
  vim \
  telnet \
  net-tools \
  inetutils-ping \
  && /ZendServer-RepositoryInstaller-linux/install_zs.sh 7.1 nginx --automatic \
  yum clean all

RUN mkdir /webapi && date +%s | sha256sum | base64 | head -c 64 | sed 's/.*/\L&/' > /webapi/secret
RUN echo "Setting Docker API key and bootstrapping Zend Server" && \
WEB_API_SECRET=$(cat /webapi/secret) && \
/usr/local/zend/bin/zendctl.sh start && \
/usr/local/zend/bin/zs-manage api-keys-add-key -n docker -s $WEB_API_SECRET && \
/usr/local/zend/bin/zs-manage bootstrap-single-server -p admin -a 'TRUE' -r FALSE -t 3 -w 5 && \
/usr/local/zend/bin/zs-manage restart -N docker -K $WEB_API_SECRET && \
/usr/local/zend/bin/zendctl.sh stop

COPY run-nginx.sh /run.sh
RUN chmod 775 /*.sh

COPY shell_functions.rc /shell_functions.rc
RUN rm -f /usr/local/zend/var/log/*.log

COPY check_lic.php /check_lic.php

EXPOSE 80
EXPOSE 443
EXPOSE 10081
EXPOSE 10082

CMD ["/run.sh"]
